# Generated by Django 5.2.7 on 2025-10-09 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Acceso')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('usos_maximos', models.IntegerField(default=1, help_text='Número máximo de veces que puede usarse este código. 0 = ilimitado', verbose_name='Usos Máximos')),
                ('usos_actuales', models.IntegerField(default=0, verbose_name='Usos Actuales')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('activo', models.BooleanField(default=True, verbose_name='Código Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Código de Acceso',
                'verbose_name_plural': 'Códigos de Acceso',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('carrera', models.CharField(default='Ingeniería Estadística e Informática', max_length=200, verbose_name='Carrera')),
                ('pin', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='El PIN debe contener exactamente 4 dígitos numéricos', regex='^\\d{4}$')], verbose_name='PIN de Acceso')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de Perfil')),
                ('algoritmo_elegido', models.CharField(blank=True, choices=[('regresion_lineal', 'Regresión Lineal'), ('regresion_logistica', 'Regresión Logística'), ('ridge_lasso', 'Ridge y Lasso'), ('arbol_cart', 'Árbol de Regresión CART'), ('knn', 'K-Nearest Neighbors Regression'), ('red_neuronal', 'Red Neuronal para Regresión')], max_length=50, null=True, verbose_name='Algoritmo Elegido')),
                ('dataset_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Dataset')),
                ('dataset_archivo', models.FileField(blank=True, null=True, upload_to='datasets/', verbose_name='Archivo Dataset')),
                ('metricas', models.JSONField(blank=True, null=True, verbose_name='Métricas del Modelo')),
                ('modelo_archivo', models.FileField(blank=True, null=True, upload_to='modelos/', verbose_name='Modelo Entrenado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Perfil Activo')),
            ],
            options={
                'verbose_name': 'Perfil de Estudiante',
                'verbose_name_plural': 'Perfiles de Estudiantes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
