version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=django-insecure-change-this-in-production
      - ALLOWED_HOSTS=*
    restart: unless-stopped

volumes:
  media:
  staticfiles:
